// Generated by cmc (check-my-code)
// Do not edit manually - regenerate with: cmc generate eslint

import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": "error",
      "no-console": "warn"
    },
  }
);
